@{
    # Build manifest for the shared web pipeline (../../web-pipeline/publish.ps1).
    # Ordered topic list drives prev/next and section-number offsets; preprocess
    # steps run first. See ../../web-pipeline/README.md for the schema.

    Preprocess = @(
        # Bit-field diagrams pandoc can't parse -> pre-rendered SVG, reused by builds.
        @{
            Kind    = 'bytefields'
            Sources = @(
                'chapters-part1/8-instructionencoding.tex',
                'chapters-part1/cheatsheet.tex'
            )
        },
        # Normalise the standalone Part 2 cheatsheet into part2.tex.
        @{
            Kind     = 'assemble'
            Out      = 'part2.tex'
            Preamble = 'cheatsheet2.tex'
            Title    = 'Computer Organisation and Architecture — Part 2'
            Sources  = @('cheatsheet2.tex')
        },
        # Slice Part 2 into one module page per top-level \section*, routing the
        # four pre-section summary tables to the module they summarise.
        @{
            Kind         = 'split'
            Source       = 'part2.tex'
            OutDir       = 'chapters-part2'
            Sections     = 'star'
            Modules      = @(
                @{ Slug = 'p2-1-arithmetic';    Title = 'Computer Arithmetic' },
                @{ Slug = 'p2-2-interfaces';    Title = 'Interfaces' },
                @{ Slug = 'p2-3-peripherals';   Title = 'Peripherals' },
                @{ Slug = 'p2-4-datatransfer';  Title = 'Data Transfer Mechanisms' },
                @{ Slug = 'p2-5-memory';        Title = 'Memory' },
                @{ Slug = 'p2-6-cache';         Title = 'Cache' },
                @{ Slug = 'p2-7-virtualmemory'; Title = 'Virtual Memory' },
                @{ Slug = 'p2-8-pipeline';      Title = 'Pipeline' }
            )
            TableRouting = @(
                @{ Caption = 'Volatile Memory Summary';             Slug = 'p2-5-memory' },
                @{ Caption = 'Non-Volatile Memory Summary';         Slug = 'p2-5-memory' },
                @{ Caption = 'Storage Architecture Comparison';     Slug = 'p2-5-memory' },
                @{ Caption = 'I/O Data Transfer Mechanisms Summary'; Slug = 'p2-4-datatransfer' }
            )
        }
    )

    Topics = @(
        # Part 1 — numbered chapters (section offsets derived from order).
        @{ Source = 'chapters-part1/1-introduction.tex';          Title = 'Introduction';                       NumberSections = $true },
        @{ Source = 'chapters-part1/2-dataorganisation.tex';      Title = 'Data Organisation in Memory';        NumberSections = $true },
        @{ Source = 'chapters-part1/3-instructionorganisation.tex'; Title = 'Instruction Organisation in Memory'; NumberSections = $true },
        @{ Source = 'chapters-part1/4-addressingmodes.tex';       Title = 'Addressing Modes';                   NumberSections = $true },
        @{ Source = 'chapters-part1/5-instructionset.tex';        Title = 'Instruction Set';                    NumberSections = $true },
        @{ Source = 'chapters-part1/6-modularprogramming.tex';    Title = 'Modular Programming';                NumberSections = $true },
        @{ Source = 'chapters-part1/7-flowcontrolconstructs.tex'; Title = 'Flow Control Constructs';            NumberSections = $true },
        @{ Source = 'chapters-part1/8-instructionencoding.tex';   Title = 'Instruction Encoding and ISA';       NumberSections = $true },
        # General Reference — unnumbered.
        @{ Source = 'chapters-part1/cheatsheet.tex';              Title = 'General Reference' },
        # Part 2 — unnumbered module pages (generated by the split step above).
        @{ Source = 'chapters-part2/p2-1-arithmetic.tex';    Title = 'Computer Arithmetic' },
        @{ Source = 'chapters-part2/p2-2-interfaces.tex';    Title = 'Interfaces' },
        @{ Source = 'chapters-part2/p2-3-peripherals.tex';   Title = 'Peripherals' },
        @{ Source = 'chapters-part2/p2-4-datatransfer.tex';  Title = 'Data Transfer Mechanisms' },
        @{ Source = 'chapters-part2/p2-5-memory.tex';        Title = 'Memory' },
        @{ Source = 'chapters-part2/p2-6-cache.tex';         Title = 'Cache' },
        @{ Source = 'chapters-part2/p2-7-virtualmemory.tex'; Title = 'Virtual Memory' },
        @{ Source = 'chapters-part2/p2-8-pipeline.tex';      Title = 'Pipeline' }
    )

    Index = @{ Source = 'index.md'; Title = 'Overview' }

    Obsolete = @(
        'part1.html', 'part1.md', 'part1.tex',
        'part1-combined.html', 'part1-combined.md',
        'reference.html', 'reference.md',
        'part2.html', 'part2.md'
    )
}
